name: Rust

on:
  workflow_dispatch:
env:
  REPO_BRANCH: master
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
#        target: [i686-pc-windows-msvc, x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
        target: [i686-pc-windows-msvc]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Generate Release Tag
        run: |
          echo "== Time：$(date +'%Y-%m-%d %H:%M:%S') =="
          echo "release_tag=$(date +"%Y.%m.%d-%H%M%S")" >> $GITHUB_OUTPUT
          touch release.txt
          echo "status=success" >> $GITHUB_OUTPUT
        
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
